# Generated by Django 4.1.2 on 2022-10-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_employee_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
